docker run -d \
  --restart=unless-stopped \
  --pull=always \
  --health-cmd="ip link | grep tun-firezone" \
  --name=firezone-gateway \
  --cap-add=NET_ADMIN \
  --volume /var/lib/firezone \
  --sysctl net.ipv4.ip_forward=1 \
  --sysctl net.ipv4.conf.all.src_valid_mark=1 \
  --sysctl net.ipv6.conf.all.disable_ipv6=0 \
  --sysctl net.ipv6.conf.all.forwarding=1 \
  --sysctl net.ipv6.conf.default.forwarding=1 \
  --device="/dev/net/tun:/dev/net/tun" \
  --env FIREZONE_TOKEN=".SFMyNTY.g2gDaANtAAAAJDIwYzdkNWIzLTMzZGEtNDUzMC1iNGZjLWNiNjk4YTc2ZWFkNW0AAAAkOTQ0NDYyYjEtM2IzYS00NWIyLTk5OWItYTBlN2QzNmM3OGNhbQAAADg3Q0kxSUhFOVZTM1RGNlI4NlBUUklGVkhPSERWSE5FTTY3UlFHUkExNUpCUVJSNzMyTTRHPT09PW4GADrXf-ePAWIAAVGA.jE9LHV1idB1TrdvlwaMwxa-mOQrPrhV4H7e_OmD52GU" \
  --env FIREZONE_ENABLE_MASQUERADE="1" \
  --env FIREZONE_NAME=$(hostname) \
  ghcr.io/firezone/gateway:1.0
